-- EventHub MySQL schema. Drops and recreates tables matching the Java code.
DROP DATABASE IF EXISTS eventhub;
CREATE DATABASE eventhub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE eventhub;

CREATE TABLE users (
  user_id          INT PRIMARY KEY AUTO_INCREMENT,
  name             VARCHAR(100)  NOT NULL,
  email            VARCHAR(150)  NOT NULL UNIQUE,
  password         VARCHAR(255)  NOT NULL,
  role             VARCHAR(20)   DEFAULT 'user',
  phone            VARCHAR(20),
  bio              TEXT,
  status           VARCHAR(20)   DEFAULT 'active',
  failed_attempts  INT           DEFAULT 0,
  reset_token      VARCHAR(255),
  reset_expiry     DATETIME,
  created_at       DATETIME      DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE events (
  event_id         INT PRIMARY KEY AUTO_INCREMENT,
  host_id          INT NOT NULL,
  title            VARCHAR(200)  NOT NULL,
  description      TEXT,
  category         VARCHAR(50),
  location         VARCHAR(255),
  event_date       DATE          NOT NULL,
  event_time       TIME,
  max_participants INT           DEFAULT 50,
  status           VARCHAR(20)   DEFAULT 'pending',
  created_at       DATETIME      DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (host_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE participants (
  participant_id   INT PRIMARY KEY AUTO_INCREMENT,
  event_id         INT NOT NULL,
  user_id          INT NOT NULL,
  status           VARCHAR(20) DEFAULT 'registered',
  joined_at        DATETIME    DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_event (user_id, event_id),
  FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,
  FOREIGN KEY (user_id)  REFERENCES users(user_id)  ON DELETE CASCADE
);

CREATE TABLE admin_actions (
  action_id        INT PRIMARY KEY AUTO_INCREMENT,
  admin_id         INT NOT NULL,
  action_type      VARCHAR(100) NOT NULL,
  target_type      VARCHAR(50),
  target_id        INT,
  notes            VARCHAR(500),
  action_at        DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (admin_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE contact_messages (
  message_id       INT PRIMARY KEY AUTO_INCREMENT,
  name             VARCHAR(100) NOT NULL,
  email            VARCHAR(150) NOT NULL,
  subject          VARCHAR(200),
  message          TEXT,
  submitted_at     DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Seed an admin account. Password is "Admin@123" hashed using PasswordUtil
-- (SHA-256 with random salt). Generated by running PasswordUtil locally.
-- Use the LoginServlet endpoint /login with email admin@eventhub.com and password Admin@123.
-- The stored hash below is regenerated by the post-deploy seed step instead, so do not rely on it.
INSERT INTO users (name, email, password, role, status)
VALUES ('Administrator', 'admin@eventhub.com', 'PLACEHOLDER', 'admin', 'active');
